---
apiVersion: v1
kind: Secret
metadata:
  name: elastic
  namespace: kube-system
type: Opaque
data:
  ELASTICSEARCH_HOST: ...
  ELASTICSEARCH_PORT: ...
  KIBANA_HOST: ...
  ELASTIC_USERNAME: ...
  ELASTIC_PASSWORD: ...
  MYSQL_ROOT_PASSWORD: ...
---
apiVersion: v1
kind: Secret
metadata:
  name: beats-demo
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ...
  MYSQL_PASSWORD: ...
